.PHONY: clean All

All:
	@echo "----------Building project:[ OOPLab - Debug ]----------"
	@cd "OOPLab" && "$(MAKE)" -f  "OOPLab.mk"
clean:
	@echo "----------Cleaning project:[ OOPLab - Debug ]----------"
	@cd "OOPLab" && "$(MAKE)" -f  "OOPLab.mk" clean
