.PHONY: clean All

All:
	@echo "----------Building project:[ Arrays - Debug ]----------"
	@"$(MAKE)" -f  "Arrays.mk"
clean:
	@echo "----------Cleaning project:[ Arrays - Debug ]----------"
	@"$(MAKE)" -f  "Arrays.mk" clean
